name: Build and Test

on:
  - push
  - pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Granting private modules access
      run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
    # We have a lot of concurrency and synchronization in this library. Test with -race and
    # -count=100 to expose any timing-related bugs.
    - name: Run unit tests
      run: |
        go test -race -count=10 -v -failfast -tags="headless" -coverprofile=profile.cov ./...
    - name: Test leaks
      run: go test -tags leaktests -run '.*Leaks' -v -args -leak-runs 10
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=profile.cov -service=github